#pragma once                                                                                                                                                                                                                                                                                   
#include <cstdint>                                                                                                                                                                                                                                                                             
#include <ostream>                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                               
enum class Contracts : int32_t {};      
                                                                                                                                                                                                                                                                                               
constexpr Contracts operator+(Contracts a, Contracts b) noexcept {                                                                                                                                                                                                                             
    return Contracts{static_cast<int32_t>(a) + static_cast<int32_t>(b)};
}                                                                                                                                                                                                                                                                                              
constexpr Contracts operator-(Contracts a, Contracts b) noexcept {                                                                                                                                                                                                                           
    return Contracts{static_cast<int32_t>(a) - static_cast<int32_t>(b)};
}                                                                                                                                                                                                                                                                                              
constexpr Contracts operator-(Contracts a) noexcept {
    return Contracts{-static_cast<int32_t>(a)};                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                                                            
constexpr Contracts& operator+=(Contracts& a, Contracts b) noexcept { return a = a + b; }                                                                                                                                                                                                      
constexpr Contracts& operator-=(Contracts& a, Contracts b) noexcept { return a = a - b; }                                                                                                                                                                                                      
                                            
constexpr Contracts operator*(Contracts a, int32_t k) noexcept {                                                                                                                                                                                                                               
    return Contracts{static_cast<int32_t>(a) * k};                                                                                                                                                                                                                                             
}                                                                                                                                                                                                                                                                                              
constexpr Contracts operator*(int32_t k, Contracts a) noexcept { return a * k; }                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                               
constexpr int32_t to_int(Contracts c) noexcept { return static_cast<int32_t>(c); }                                                                                                                                                                                                             
                                        
inline std::ostream& operator<<(std::ostream& os, Contracts c) {                                                                                                                                                                                                                               
    return os << static_cast<int32_t>(c);                                                                                                                                                                                                                                                      
}